config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "projects#index"


  resources :projects
  # replaces:
  # get "/projects", to: "projects#index"
  # get "/projects/:id", to: "projects#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :comments
  has_many :technologies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :start_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectPlanner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<div class="container w-50">

  <div class="animated-banner">

    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1200 310" style="enable-background:new 0 0 1200 310;" xml:space="preserve" preserveAspectRatio="xMinYMin slice">
      <defs>
        <filter id="f1" x="0" y="0">
          <feGaussianBlur in="SourceGraphic" stdDeviation="3" />
        </filter>
        <linearGradient id="GRAD_OVERLAY" gradientUnits="userSpaceOnUse" x1="100%" y1="0%" x2="0%" y2="100%">
          <stop offset="0" style="stop-color:#000000;stop-opacity:0.40"/>
          <stop offset="1" style="stop-color:#000000;stop-opacity:0.00"/>
        </linearGradient>
        <linearGradient id="GRAD_1">
          <stop offset="0" style="stop-color:#FFFFFF;stop-opacity:0.30"/>
          <stop offset="1" style="stop-color:#FFFFFF;stop-opacity:0.00"/>
        </linearGradient>
        <linearGradient id="GRAD_2" x1="0" y1="1" y2="0" x2="1">
          <stop offset="0" style="stop-color:#FFFFFF;stop-opacity:0.00"/>
          <stop offset="1" style="stop-color:#FFFFFF;stop-opacity:0.20"/>
        </linearGradient>
        <linearGradient id="GRAD_3">
          <stop offset="0" style="stop-color:#FFFFFF;stop-opacity:0.00"/>
          <stop offset="1" style="stop-color:#FFFFFF;stop-opacity:0.20"/>
        </linearGradient>
        <linearGradient id="GRAD_4" y2="1" x2="1">
          <stop offset="0" style="stop-color:#FFFFFF;stop-opacity:0.00"/>
          <stop offset="1" style="stop-color:#FFFFFF;stop-opacity:0.20"/>
        </linearGradient>
    </defs>
      <g id="background">
        <rect y="-1" class="st1" width="1200" height="312"/>
        <rect y="0" class="st0" width="1200" height="312"/>
      </g>
      <g id="graphic">
        <polygon class="st1" points="848.875,311 310.808,311 579.841,-25.535"/>
        <polygon class="st2" points="0,-1 0,311 42.081,311 293.299,-1"/>
        <polygon class="st3" points="310.807,311 0,311 -0.346,-67.654"/>
      </g>
     <g id="line">
      <polyline class="st4" points="1054.599,310.25 832.676,30.608 610.333,310.25 761.278,310.25 611.459,121.124 461.785,310.25"/>
        <polyline class="st5" points="1054.599,310.25 832.676,30.608 610.333,310.25 761.278,310.25 611.459,121.124 461.785,310.25"/>
       <polyline class="st6" points="1054.599,310.25 832.676,30.608 610.333,310.25 761.278,310.25 611.459,121.124 461.785,310.25"/>
     </g>
  </svg>
  </div>

  <h1>List of upcoming coding projects</h1>

    <% @projects.each do |prj| %>
        <div class="card-product m-5 p-2">
          <img src="https://media.istockphoto.com/vectors/innovation-or-innovative-idea-symbol-linear-icon-vector-id1147358759?k=6&m=1147358759&s=612x612&w=0&h=kdyU_fYNeNX-Cm_CBF9JnDw9Zn120WmSxwqUUlatl8U=" alt="">
          <div class="card-product-infos">
        <%= prj.title %> |
        <%= prj.description %> | 
        <%= link_to "See moooar", project_path(prj), class: "btn btn-info btn-sm pull-right"  %>
        <%= link_to "Delete this", project_path(prj), method: :delete, class: "btn btn-light btn-sm pull-right"  %>
        </div>
      </div>
    <% end %>

      <button class="add-project">
        <%= link_to "Add new Project", new_project_path %>
      </button>
</div>

app/views/projects/new.html.erb
<script>
$('#datepicker').datepicker({format: 'yyyy-mm-dd'});
</script>

<div class="container w-25">
  <%= simple_form_for @project do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :start_date %>

    <%= f.button :submit %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <h1>Details on a Project "<%= @project.title %>"</h1>

  <ul>
    <p>Title: <%= @project.title %></p>
    <p>Details: <%= @project.description %></p>
    <p>Start Date: <%= @project.start_date %> </p>
    <button class="small-button"><%= link_to "Back to all projects", root_path %></button>
  </ul>
</div>